# Generated by Django 5.0 on 2023-12-22 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='drinks',
            new_name='Drink',
        ),
    ]
